# Generated by Django 3.0 on 2020-01-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[(11, 'Etudiant'), (12, 'Professeur'), (13, 'Entreprise')], max_length=50),
        ),
    ]
