# Generated by Django 3.0 on 2020-01-27 01:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], unique=True)),
                ('description', models.TextField()),
                ('key_words', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25), size=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='corrections/%Y/%m/$D/')),
            ],
        ),
        migrations.DeleteModel(
            name='Exercice',
        ),
    ]
