# Generated by Django 3.0 on 2020-01-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('language', models.CharField(choices=[(11, 'Python'), (12, 'R')], max_length=50)),
                ('abstract', models.TextField()),
                ('starting_date', models.DateField(blank=None)),
                ('ending_date', models.DateField(blank=None)),
                ('is_coding_game', models.BooleanField(default=False)),
                ('allocated_time', models.TimeField()),
                ('subject', models.CharField(max_length=120)),
                ('contact_mail', models.EmailField(max_length=120)),
                ('pseudo', models.CharField(max_length=120)),
                ('auto_correction', models.BooleanField(default=False)),
            ],
        ),
    ]
