# Generated by Django 3.0.3 on 2020-03-29 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('language', models.CharField(choices=[('4', 'Python'), ('5', 'R')], max_length=50)),
                ('starting_date', models.DateField(blank=True)),
                ('ending_date', models.DateField(blank=True)),
                ('challenge_type', models.CharField(choices=[('1', 'Coding Game'), ('2', 'Professional'), ('3', 'Community')], max_length=50)),
                ('allocated_time', models.TimeField(blank=True, null=True)),
                ('contact_mail', models.EmailField(max_length=120)),
                ('auto_correction', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
