# Generated by Django 3.0 on 2020-01-26 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='abstract',
        ),
    ]
