# Generated by Django 3.0 on 2020-01-28 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0003_auto_20200126_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='language',
            field=models.IntegerField(choices=[(13, 'Python'), (14, 'R')]),
        ),
    ]
