# Generated by Django 3.0 on 2020-01-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_auto_20200128_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='is_coding_game',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='pseudo',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='subject',
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenge_type',
            field=models.CharField(choices=[(1, 'Coding Game'), (2, 'Professional'), (3, 'Community')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='language',
            field=models.IntegerField(choices=[(4, 'Python'), (5, 'R')]),
        ),
    ]
