# Generated by Django 3.0 on 2020-01-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_auto_20200130_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challenge_type',
            field=models.CharField(choices=[(1, 'Coding Game'), (2, 'Professional'), (3, 'Community')], max_length=50),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='language',
            field=models.CharField(choices=[(4, 'Python'), (5, 'R')], max_length=50),
        ),
    ]
